const Order = require('../../examples/order/bo/order');

test('Bo#parseFromDatabase where multiple rows reduce to one nested object (with all one-to-one or one-to-many tables)', () => {
  const results = [{
    'order#id': 3866,
    'order#email': 'email@example.com',
    'order#browser_ip': void 0,
    'order#browser_user_agent': void 0,
    'order#kujo_imported_date': '2018-08-13 12:40:05.909355-04',
    'order#created_date': '2018-06-08 17:51:27-04',
    'order#cancel_reason': void 0,
    'order#cancelled_date': void 0,
    'order#closed_date': '2018-06-11 17:34:27-04',
    'order#processed_date': '2018-06-08 17:51:27-04',
    'order#updated_date': '2018-06-13 15:41:55-04',
    'order#note': void 0,
    'order#subtotal_price': 0.00,
    'order#taxes_included': false,
    'order#total_discounts': 625.00,
    'order#total_price': 0.00,
    'order#total_tax': 0.00,
    'order#total_weight': 0,
    'order#order_status_url': 'example.com/order',
    'order#utm_source_id': 6,
    'order#utm_medium_id': void 0,
    'order#utm_campaign': void 0,
    'order#utm_content': void 0,
    'order#utm_term': void 0,
    'utm_source#id': 6,
    'utm_source#value': 'instagram',
    'utm_source#label': 'Instagram',
    'utm_source#internal': true,
    'line_item#id': 2271,
    'line_item#fulfillment_status_id': 7,
    'line_item#product_variant_id': 163,
    'line_item#order_id': 3866,
    'line_item#fulfillable_quantity': 0,
    'line_item#fulfillment_service': 'manual',
    'line_item#grams': 0,
    'line_item#price': 120.00,
    'line_item#quantity': 1,
    'line_item#requires_shipping': void 0,
    'line_item#taxable': true,
    'line_item#total_discount': 0.00,
    'product_variant#id': 163,
    'product_variant#product_id': 1,
    'product_variant#actual_product_variant_id': 98,
    'product_variant#color_id': 3,
    'product_variant#gender_id': 1,
    'product_variant#size_id': 11,
    'product_variant#barcode': void 0,
    'product_variant#price': 120,
    'product_variant#compare_at_price': 120,
    'product_variant#created_date': '2018-07-17 13:20:29.202352-04',
    'product_variant#updated_date': '2018-07-17 13:20:29.202352-04',
    'product_variant#grams': void 0,
    'product_variant#requires_shipping': void 0,
    'product#id': 1,
    'product#vendor_id': 1,
    'product#value': 'mens_yard_shoes',
    'product#label': 'Mens Yard Shoes',
    'product#product_type': 'shoes',
    'product#created_date': '2018-06-21 12:38:39.021271-04',
    'product#updated_date': '2018-06-21 12:38:39.021271-04',
    'product#published_date': void 0,
    'product#category': void 0,
  }, {
    'order#id': 3866,
    'order#email': 'email@example.com',
    'order#browser_ip': void 0,
    'order#browser_user_agent': void 0,
    'order#kujo_imported_date': '2018-08-13 12:40:05.909355-04',
    'order#created_date': '2018-06-08 17:51:27-04',
    'order#cancel_reason': void 0,
    'order#cancelled_date': void 0,
    'order#closed_date': '2018-06-11 17:34:27-04',
    'order#processed_date': '2018-06-08 17:51:27-04',
    'order#updated_date': '2018-06-13 15:41:55-04',
    'order#note': void 0,
    'order#subtotal_price': 0.00,
    'order#taxes_included': false,
    'order#total_discounts': 625.00,
    'order#total_price': 0.00,
    'order#total_tax': 0.00,
    'order#total_weight': 0,
    'order#order_status_url': 'example.com/order',
    'order#utm_source_id': 6,
    'order#utm_medium_id': void 0,
    'order#utm_campaign': void 0,
    'order#utm_content': void 0,
    'order#utm_term': void 0,
    'utm_source#id': 6,
    'utm_source#value': 'instagram',
    'utm_source#label': 'Instagram',
    'utm_source#internal': true,
    'line_item#id': 2272,
    'line_item#fulfillment_status_id': 7,
    'line_item#product_variant_id': 186,
    'line_item#order_id': 3866,
    'line_item#fulfillable_quantity': 0,
    'line_item#fulfillment_service': 'manual',
    'line_item#grams': 0,
    'line_item#price': 120.00,
    'line_item#quantity': 1,
    'line_item#requires_shipping': void 0,
    'line_item#taxable': true,
    'line_item#total_discount': 0.00,
    'product_variant#id': 186,
    'product_variant#product_id': 1,
    'product_variant#actual_product_variant_id': 111,
    'product_variant#color_id': 4,
    'product_variant#gender_id': 1,
    'product_variant#size_id': 11,
    'product_variant#barcode': void 0,
    'product_variant#price': 120,
    'product_variant#compare_at_price': 120,
    'product_variant#created_date': '2018-07-17 13:20:29.236344-04',
    'product_variant#updated_date': '2018-07-17 13:20:29.236344-04',
    'product_variant#grams': void 0,
    'product_variant#requires_shipping': void 0,
    'product#id': 1,
    'product#vendor_id': 1,
    'product#value': 'mens_yard_shoes',
    'product#label': 'Mens Yard Shoes',
    'product#product_type': 'shoes',
    'product#created_date': '2018-06-21 12:38:39.021271-04',
    'product#updated_date': '2018-06-21 12:38:39.021271-04',
    'product#published_date': void 0,
    'product#category': void 0,
  }, {
    'order#id': 3866,
    'order#email': 'email@example.com',
    'order#browser_ip': void 0,
    'order#browser_user_agent': void 0,
    'order#kujo_imported_date': '2018-08-13 12:40:05.909355-04',
    'order#created_date': '2018-06-08 17:51:27-04',
    'order#cancel_reason': void 0,
    'order#cancelled_date': void 0,
    'order#closed_date': '2018-06-11 17:34:27-04',
    'order#processed_date': '2018-06-08 17:51:27-04',
    'order#updated_date': '2018-06-13 15:41:55-04',
    'order#note': void 0,
    'order#subtotal_price': 0.00,
    'order#taxes_included': false,
    'order#total_discounts': 625.00,
    'order#total_price': 0.00,
    'order#total_tax': 0.00,
    'order#total_weight': 0,
    'order#order_status_url': 'example.com/order',
    'order#utm_source_id': 6,
    'order#utm_medium_id': void 0,
    'order#utm_campaign': void 0,
    'order#utm_content': void 0,
    'order#utm_term': void 0,
    'utm_source#id': 6,
    'utm_source#value': 'instagram',
    'utm_source#label': 'Instagram',
    'utm_source#internal': true,
    'line_item#id': 2273,
    'line_item#fulfillment_status_id': 7,
    'line_item#product_variant_id': 213,
    'line_item#order_id': 3866,
    'line_item#fulfillable_quantity': 0,
    'line_item#fulfillment_service': 'manual',
    'line_item#grams': 0,
    'line_item#price': 120.00,
    'line_item#quantity': 1,
    'line_item#requires_shipping': void 0,
    'line_item#taxable': true,
    'line_item#total_discount': 0.00,
    'product_variant#id': 213,
    'product_variant#product_id': 1,
    'product_variant#actual_product_variant_id': 127,
    'product_variant#color_id': 1,
    'product_variant#gender_id': 1,
    'product_variant#size_id': 11,
    'product_variant#barcode': void 0,
    'product_variant#price': 120,
    'product_variant#compare_at_price': 120,
    'product_variant#created_date': '2018-07-17 13:20:29.27225-04',
    'product_variant#updated_date': '2018-07-17 13:20:29.27225-04',
    'product_variant#grams': void 0,
    'product_variant#requires_shipping': void 0,
    'product#id': 1,
    'product#vendor_id': 1,
    'product#value': 'mens_yard_shoes',
    'product#label': 'Mens Yard Shoes',
    'product#product_type': 'shoes',
    'product#created_date': '2018-06-21 12:38:39.021271-04',
    'product#updated_date': '2018-06-21 12:38:39.021271-04',
    'product#published_date': void 0,
    'product#category': void 0,
  }, {
    'order#id': 3866,
    'order#email': 'email@example.com',
    'order#browser_ip': void 0,
    'order#browser_user_agent': void 0,
    'order#kujo_imported_date': '2018-08-13 12:40:05.909355-04',
    'order#created_date': '2018-06-08 17:51:27-04',
    'order#cancel_reason': void 0,
    'order#cancelled_date': void 0,
    'order#closed_date': '2018-06-11 17:34:27-04',
    'order#processed_date': '2018-06-08 17:51:27-04',
    'order#updated_date': '2018-06-13 15:41:55-04',
    'order#note': void 0,
    'order#subtotal_price': 0.00,
    'order#taxes_included': false,
    'order#total_discounts': 625.00,
    'order#total_price': 0.00,
    'order#total_tax': 0.00,
    'order#total_weight': 0,
    'order#order_status_url': 'example.com/order',
    'order#utm_source_id': 6,
    'order#utm_medium_id': void 0,
    'order#utm_campaign': void 0,
    'order#utm_content': void 0,
    'order#utm_term': void 0,
    'utm_source#id': 6,
    'utm_source#value': 'instagram',
    'utm_source#label': 'Instagram',
    'utm_source#internal': true,
    'line_item#id': 2274,
    'line_item#fulfillment_status_id': 7,
    'line_item#product_variant_id': 207,
    'line_item#order_id': 3866,
    'line_item#fulfillable_quantity': 0,
    'line_item#fulfillment_service': 'manual',
    'line_item#grams': 0,
    'line_item#price': 120.00,
    'line_item#quantity': 1,
    'line_item#requires_shipping': void 0,
    'line_item#taxable': true,
    'line_item#total_discount': 0.00,
    'product_variant#id': 207,
    'product_variant#product_id': 1,
    'product_variant#actual_product_variant_id': 124,
    'product_variant#color_id': 1,
    'product_variant#gender_id': 1,
    'product_variant#size_id': 8,
    'product_variant#barcode': void 0,
    'product_variant#price': 120,
    'product_variant#compare_at_price': 120,
    'product_variant#created_date': '2018-07-17 13:20:29.261909-04',
    'product_variant#updated_date': '2018-07-17 13:20:29.261909-04',
    'product_variant#grams': void 0,
    'product_variant#requires_shipping': void 0,
    'product#id': 1,
    'product#vendor_id': 1,
    'product#value': 'mens_yard_shoes',
    'product#label': 'Mens Yard Shoes',
    'product#product_type': 'shoes',
    'product#created_date': '2018-06-21 12:38:39.021271-04',
    'product#updated_date': '2018-06-21 12:38:39.021271-04',
    'product#published_date': void 0,
    'product#category': void 0,
  }, {
    'order#id': 3866,
    'order#email': 'email@example.com',
    'order#browser_ip': void 0,
    'order#browser_user_agent': void 0,
    'order#kujo_imported_date': '2018-08-13 12:40:05.909355-04',
    'order#created_date': '2018-06-08 17:51:27-04',
    'order#cancel_reason': void 0,
    'order#cancelled_date': void 0,
    'order#closed_date': '2018-06-11 17:34:27-04',
    'order#processed_date': '2018-06-08 17:51:27-04',
    'order#updated_date': '2018-06-13 15:41:55-04',
    'order#note': void 0,
    'order#subtotal_price': 0.00,
    'order#taxes_included': false,
    'order#total_discounts': 625.00,
    'order#total_price': 0.00,
    'order#total_tax': 0.00,
    'order#total_weight': 0,
    'order#order_status_url': 'example.com/order',
    'order#utm_source_id': 6,
    'order#utm_medium_id': void 0,
    'order#utm_campaign': void 0,
    'order#utm_content': void 0,
    'order#utm_term': void 0,
    'utm_source#id': 6,
    'utm_source#value': 'instagram',
    'utm_source#label': 'Instagram',
    'utm_source#internal': true,
    'line_item#id': 2275,
    'line_item#fulfillment_status_id': 7,
    'line_item#product_variant_id': 296,
    'line_item#order_id': 3866,
    'line_item#fulfillable_quantity': 0,
    'line_item#fulfillment_service': 'manual',
    'line_item#grams': 0,
    'line_item#price': 25.00,
    'line_item#quantity': 1,
    'line_item#requires_shipping': void 0,
    'line_item#taxable': true,
    'line_item#total_discount': 0.00,
    'product_variant#id': 296,
    'product_variant#product_id': 5,
    'product_variant#actual_product_variant_id': 144,
    'product_variant#color_id': 5,
    'product_variant#gender_id': 3,
    'product_variant#size_id': 21,
    'product_variant#barcode': void 0,
    'product_variant#price': 120,
    'product_variant#compare_at_price': 120,
    'product_variant#created_date': '2018-07-17 13:20:29.387943-04',
    'product_variant#updated_date': '2018-07-17 13:20:29.387943-04',
    'product_variant#grams': void 0,
    'product_variant#requires_shipping': void 0,
    'product#id': 5,
    'product#vendor_id': 1,
    'product#value': 'relaxed_tee',
    'product#label': 'Relaxed Tee',
    'product#product_type': 'shirts',
    'product#created_date': '2018-06-21 12:44:30.640995-04',
    'product#updated_date': '2018-06-21 12:44:30.640995-04',
    'product#published_date': void 0,
    'product#category': void 0,
  }, {
    'order#id': 3866,
    'order#email': 'email@example.com',
    'order#browser_ip': void 0,
    'order#browser_user_agent': void 0,
    'order#kujo_imported_date': '2018-08-13 12:40:05.909355-04',
    'order#created_date': '2018-06-08 17:51:27-04',
    'order#cancel_reason': void 0,
    'order#cancelled_date': void 0,
    'order#closed_date': '2018-06-11 17:34:27-04',
    'order#processed_date': '2018-06-08 17:51:27-04',
    'order#updated_date': '2018-06-13 15:41:55-04',
    'order#note': void 0,
    'order#subtotal_price': 0.00,
    'order#taxes_included': false,
    'order#total_discounts': 625.00,
    'order#total_price': 0.00,
    'order#total_tax': 0.00,
    'order#total_weight': 0,
    'order#order_status_url': 'example.com/order',
    'order#utm_source_id': 6,
    'order#utm_medium_id': void 0,
    'order#utm_campaign': void 0,
    'order#utm_content': void 0,
    'order#utm_term': void 0,
    'utm_source#id': 6,
    'utm_source#value': 'instagram',
    'utm_source#label': 'Instagram',
    'utm_source#internal': true,
    'line_item#id': 2276,
    'line_item#fulfillment_status_id': 7,
    'line_item#product_variant_id': 308,
    'line_item#order_id': 3866,
    'line_item#fulfillable_quantity': 0,
    'line_item#fulfillment_service': 'manual',
    'line_item#grams': 0,
    'line_item#price': 120.00,
    'line_item#quantity': 1,
    'line_item#requires_shipping': void 0,
    'line_item#taxable': true,
    'line_item#total_discount': 0.00,
    'product_variant#id': 308,
    'product_variant#product_id': 3,
    'product_variant#actual_product_variant_id': 157,
    'product_variant#color_id': 2,
    'product_variant#gender_id': 2,
    'product_variant#size_id': 4,
    'product_variant#barcode': void 0,
    'product_variant#price': 120,
    'product_variant#compare_at_price': 120,
    'product_variant#created_date': '2018-08-20 22:58:48.817847-04',
    'product_variant#updated_date': '2018-08-20 22:58:48.817847-04',
    'product_variant#grams': void 0,
    'product_variant#requires_shipping': void 0,
    'product#id': 3,
    'product#vendor_id': 1,
    'product#value': 'womens_yard_shoes',
    'product#label': 'Womens Yard Shoes',
    'product#product_type': 'shoes',
    'product#created_date': '2018-06-21 12:44:30.631046-04',
    'product#updated_date': '2018-06-21 12:44:30.631046-04',
    'product#published_date': void 0,
    'product#category': void 0,
  }];
  const order = Order.createOneFromDatabase(results);
  expect(Array.isArray(order)).toBe(false);
  expect(order.id).toEqual(3866);
  expect(order.utmSource.id).toEqual(6);
  expect(order.lineItems.models.length).toEqual(6);

  expect(order.lineItems.models[0].id).toEqual(2271);
  expect(order.lineItems.models[0].productVariant.id).toEqual(163);
  expect(order.lineItems.models[0].productVariant.product.id).toEqual(1);

  expect(order.lineItems.models[1].id).toEqual(2272);
  expect(order.lineItems.models[1].productVariant.id).toEqual(186);
  expect(order.lineItems.models[1].productVariant.product.id).toEqual(1);

  expect(order.lineItems.models[2].id).toEqual(2273);
  expect(order.lineItems.models[2].productVariant.id).toEqual(213);
  expect(order.lineItems.models[2].productVariant.product.id).toEqual(1);

  expect(order.lineItems.models[3].id).toEqual(2274);
  expect(order.lineItems.models[3].productVariant.id).toEqual(207);
  expect(order.lineItems.models[3].productVariant.product.id).toEqual(1);

  expect(order.lineItems.models[4].id).toEqual(2275);
  expect(order.lineItems.models[4].productVariant.id).toEqual(296);
  expect(order.lineItems.models[4].productVariant.product.id).toEqual(5);

  expect(order.lineItems.models[5].id).toEqual(2276);
  expect(order.lineItems.models[5].productVariant.id).toEqual(308);
  expect(order.lineItems.models[5].productVariant.product.id).toEqual(3);
});

test('Bo#parseFromDatabase where multiple rows reduce to one nested object (with many-to-many tables)', () => {
  // Use article page with `getBySlug` or whatever
  expect(1).toEqual(1);
});
